package uk.ac.rgu.weather.data;

/**
 * This class provides details of the weather forecast for a specific hour of a specific day.
 */
public class HourForecast {

    // the forecasted temperature in degrees celcius
    private int temperature;
    // the forecasted humidity (between 0 and 100 %)
    private int humidity;
    // the date the forecast applies for, formatted as day-month
    private String date;
    // the hour of the date that the forecast applies for (between 0 and 23)
    private int hour;
    // the weather as generated by RandomWeatherForecastGetter
    private String weather;
    // icon for the weather
    private String weatherIcon;

    /**
     * Default Constructor
     */
    public HourForecast() {
        super();
    }

    public int getTemperature() {
        return temperature;
    }

    public void setTemperature(int temperature) {
        this.temperature = temperature;
    }

    public int getHumidity() {
        return humidity;
    }

    public void setHumidity(int humidity) {
        this.humidity = humidity;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public int getHour() {
        return hour;
    }

    public void setHour(int hour) {
        this.hour = hour;
    }

    public String getWeather() {
        return weather;
    }

    public void setWeather(String weather) {
        this.weather = weather;
    }

    public String getWeatherIcon() {
        return weatherIcon;
    }

    public void setWeatherIcon(String weatherIcon) {
        this.weatherIcon = weatherIcon;
    }

    @Override
    public String toString() {
        return "HourForecast{" +
                "temperature=" + temperature +
                ", humidity=" + humidity +
                ", date='" + date + '\'' +
                ", hour=" + hour +
                ", weather='" + weather + '\'' +
                '}';
    }
}
